title: Double Yellows
description: A blog about lines and where to draw them.
url: "https://doubleyellows.net"
baseurl: ""
author: Double Yellows

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

giscus:
  repo: "doubleyellows/blog"
  repo_id: "R_kgDORQLyDw"
  category: "Announcements"
  category_id: "DIC_kwDORQLyD84C2a2k"
  mapping: "pathname"
  reactions_enabled: "1"
  emit_metadata: "0"
  theme: "light"
  lang: "en"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
